In [6]:


import requests
import json
import pandas as pd
import streamlit as st

headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": ['CUUR0000SA0L1E','CEU0000000001','CEU0500000003','LNU04000000'],"startyear":"2020", "endyear":"2025"})
p = requests.post('https://api.bls.gov/publicAPI/v1/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
rows = []
for series in json_data['Results']['series']:
    seriesId = series['seriesID'] 
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        footnotes = ",".join(
            fn["text"] for fn in item.get("footnotes", []) if fn
        )
        if 'M01' <= period <= 'M12':
            rows.append({
                "seriesID": seriesId,
                "year": year,
                "period": period,
                "value": value,
                "footnotes": footnotes
            })
df = pd.DataFrame(rows)
df['month'] = df['period'].str.replace("M", "", regex=False)
df['month'] = df['month'].astype(int)
df['date'] = pd.to_datetime(df["year"].astype(str) + "-" + df["month"].astype(str), format="%Y-%m")
df

           seriesID  year period    value footnotes  month       date
0    CUUR0000SA0L1E  2025    M09  330.804                9 2025-09-01
1    CUUR0000SA0L1E  2025    M08  329.970                8 2025-08-01
2    CUUR0000SA0L1E  2025    M07  328.980                7 2025-07-01
3    CUUR0000SA0L1E  2025    M06  328.364                6 2025-06-01
4    CUUR0000SA0L1E  2025    M05  327.509                5 2025-05-01
..              ...   ...    ...      ...       ...    ...        ...
271     LNU04000000  2020    M05     13.0                5 2020-05-01
272     LNU04000000  2020    M04     14.4                4 2020-04-01
273     LNU04000000  2020    M03      4.5                3 2020-03-01
274     LNU04000000  2020    M02      3.8                2 2020-02-01
275     LNU04000000  2020    M01      4.0                1 2020-01-01

[276 rows x 7 columns]

In [ ]:

df.to_csv(r"C:\Users\katel\bls.csv", index=False)

""" CUUR0000SA0L1E = All items less food and energy in U.S. city average, all urban consumers, not seasonally adjusted
CEU0000000001 = All employees, thousands, total nonfarm, not seasonally adjusted
CEU0500000003 = Average hourly earnings of all employees, total private, not seasonally adjusted
LNU04000000 = (Unadj) Unemployment Rate'"""

" CUUR0000SA0L1E = All items less food and energy in U.S. city average, all urban consumers, not seasonally adjusted\nCEU0000000001 = All employees, thousands, total nonfarm, not seasonally adjusted\nCEU0500000003 = Average hourly earnings of all employees, total private, not seasonally adjusted\nLNU04000000 = (Unadj) Unemployment Rate'"

In [ ]:

df

          seriesID  year period  value footnotes  month       date
0    APU0000703111  2025    M09  6.326                9 2025-09-01
1    APU0000703111  2025    M08  6.626                8 2025-08-01
2    APU0000703111  2025    M07  6.338                7 2025-07-01
3    APU0000703111  2025    M06  6.103                6 2025-06-01
4    APU0000703111  2025    M05  6.018                5 2025-05-01
..             ...   ...    ...    ...       ...    ...        ...
133  CEU0800000003  2020    M05  29.54                5 2020-05-01
134  CEU0800000003  2020    M04  30.09                4 2020-04-01
135  CEU0800000003  2020    M03  28.74                3 2020-03-01
136  CEU0800000003  2020    M02  28.64                2 2020-02-01
137  CEU0800000003  2020    M01  28.35                1 2020-01-01

[138 rows x 7 columns]

In [ ]:
import requests
import json
import prettytable

headers = {'Content-type': 'application/json'}
data = json.dumps({
    "seriesid": ['CUUR0000SA0','SUUR0000SA0'],
    "startyear": "2011",
    "endyear": "2014"
})

# --- MAKE THE API REQUEST ---
p = requests.post(
    'https://api.bls.gov/publicAPI/v2/timeseries/data/',
    data=data,
    headers=headers
)

# --- LOAD THE JSON RESPONSE ---
json_data = json.loads(p.text)

# --- PRINT THE RESPONSE TO SEE WHAT YOU GOT ---
print(json.dumps(json_data, indent=4))

# --- CHECK FOR ERRORS BEFORE PROCESSING ---
if "Results" not in json_data or "series" not in json_data["Results"]:
    print("\n❌ API did NOT return series data.")
    print("Message from BLS:", json_data.get("message", "No message provided"))
    exit()

# --- PROCESS THE DATA ---
for series in json_data["Results"]["series"]:
    x = prettytable.PrettyTable(["series id", "year", "period", "value", "footnotes"])
    seriesId = series["seriesID"]

    for item in series["data"]:
        year = item["year"]
        period = item["period"]
        value = item["value"]

        footnotes = ""
        for footnote in item["footnotes"]:
            if footnote:
                footnotes += footnote["text"] + ","

        if "M01" <= period <= "M12":
            x.add_row([seriesId, year, period, value, footnotes[:-1]])

    print(x)

{
    "status": "REQUEST_NOT_PROCESSED",
    "responseTime": 0,
    "message": [
        "Request could not be serviced, as the daily threshold for total number of requests allocated to the user with registration key  has been reached."
    ],
    "Results": {}
}

❌ API did NOT return series data.
Message from BLS: ['Request could not be serviced, as the daily threshold for total number of requests allocated to the user with registration key  has been reached.']

KeyError: 'series'

:

In [3]:
import pandas as pd

# Example data
data = [
    {"seriesID": "APU0000703111", "year": 2025, "period": "M09", "value": 6.326, "footnotes": ""},
    {"seriesID": "APU0000703111", "year": 2025, "period": "M08", "value": 6.626, "footnotes": ""},
    {"seriesID": "APU0000703111", "year": 2025, "period": "M07", "value": 6.338, "footnotes": ""},
    {"seriesID": "CEU0800000003", "year": 2020, "period": "M05", "value": 29.54, "footnotes": ""},
    {"seriesID": "CEU0800000003", "year": 2020, "period": "M04", "value": 30.09, "footnotes": ""},
    {"seriesID": "CEU0800000003", "year": 2020, "period": "M03", "value": 28.74, "footnotes": ""},
]

# Create DataFrame
df = pd.DataFrame(data)

# Add month column
df['month'] = df['period'].str.replace("M", "").astype(int)

# Add date column
df['date'] = pd.to_datetime(df["year"].astype(str) + "-" + df["month"].astype(str))

# Save to CSV
df.to_csv(r"C:\Users\katel\bls_sample.csv", index=False)

print(df)

        seriesID  year period   value footnotes  month       date
0  APU0000703111  2025    M09   6.326                9 2025-09-01
1  APU0000703111  2025    M08   6.626                8 2025-08-01
2  APU0000703111  2025    M07   6.338                7 2025-07-01
3  CEU0800000003  2020    M05  29.540                5 2020-05-01
4  CEU0800000003  2020    M04  30.090                4 2020-04-01
5  CEU0800000003  2020    M03  28.740                3 2020-03-01